source "https://rubygems.org"

gem "activesupport"
gem "eventmachine", "1.2.7", git: "https://github.com/eventmachine/eventmachine", tag: "v1.2.7"
gem "haml"
gem "ruby-metrics"
gem "rubyzip"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-websocket"
gem "thin"
