source 'https://rubygems.org'

# gem 'activesupport'
gem 'eventmachine'
gem 'haml'
gem 'ruby-metrics'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'thin'
gem 'prometheus-client'
gem 'awesome_print'
