require 'constants'
require 'support'
require 'util'

require 'control.combinator'
require 'control.command'
require 'control.config'
require 'control.console-chat'
require 'control.console-command'
require 'control.entity'
require 'control.gui'
require 'control.init'
require 'control.logistics'
require 'control.master'
require 'control.research'
require 'control.servers'
require 'control.shortcuts'

require 'control.remote'
